// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jijtsfgzmpxqfqwxyqnv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImppanRzZmd6bXB4cWZxd3h5cW52Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU0NTIwMTksImV4cCI6MjA2MTAyODAxOX0.2Ezq6s1ZlX9v2zZXCXCurkoCVU4bYyq2xJlg8HZu1bQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
